name=RoboFlow
version=1.0.3
author=Souhardo Das
maintainer=Souhardo Das <souhardodasdps1@gmail.com>
sentence=Rule-based robotics framework for Arduino with manual and autonomous modes.
paragraph=RoboFlow introduces declarative robotics. Define robot behavior using human-readable rules with support for autonomous, manual, and hybrid control.
category=Device Control
url=https://github.com/souhardodas/RoboFlow
architectures=*
